### PR TITLE
#1 - Added olegmoz & olenagerasimova to list of architect

### PR DESCRIPTION
**Pull request by olegmoz**

### CODE REVIEW

**Comment by olegmoz** [comment]
@rultor release, tag=`0.3.10`

**Comment by olegmoz** [comment]
@yegor256 could you please touch `.rultor`, so it will be possible to create new release?

**Comment by yegor256** [comment]
@olegmoz done in e8fb7d4

**Comment by olegmoz** [comment]
@yegor256 thanks!

**Pull request merged**
