### PR TITLE
Add jacoco report generation

### PR DESCRIPTION
**Pull request by victornoel**
This is one missing thing for artipie/npm-adater#52.

Sorry @g4s8 for the extra PR :)

### CODE REVIEW

**Comment by victornoel** [comment]
@g4s8 once it is merged, can you release a new version of the ppom? Thx!

**Comment by victornoel** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@rultor release, tag=`0.3.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.3.3`

**Comment by victornoel** [comment]
@g4s8 it didn't seem to work, can we get a release? thx :)

**Comment by g4s8** [comment]
@victornoel there are some issues with xml formatting: https://www.rultor.com/t/22048-628619791

**Comment by victornoel** [comment]
@g4s8 see #22 for an issue, I will wait for it to be solved then

**Pull request merged**
